apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    artifact.spinnaker.io/location: '"${NAMESPACE}"'
    artifact.spinnaker.io/name: '"armory-orca"'
    artifact.spinnaker.io/type: '"kubernetes/deployment"'
    moniker.spinnaker.io/application: '"armory"'
    moniker.spinnaker.io/cluster: '"orca"'
  name: orca
  namespace: ${NAMESPACE}
  labels:
    app: orca
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  replicas: 1
  selector:
    matchLabels:
      app: orca
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: '"${NAMESPACE}"'
        artifact.spinnaker.io/name: '"armory-orca"'
        artifact.spinnaker.io/type: '"kubernetes/deployment"'
        moniker.spinnaker.io/application: '"armory"'
        moniker.spinnaker.io/cluster: '"orca"'
      labels:
        app: orca
    spec:
      containers:
      - name: orca
        image: docker.io/armory/spinnaker-orca-slim:${orca_version}
        command: ["bash", "-c"]
        args: ["chmod 755 /opt/spinnaker/config/default/fetch.sh && /opt/spinnaker/config/default/fetch.sh && /opt/orca/bin/orca"]
        envFrom:
        - configMapRef:
            name: init-env
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 3
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
        - name: default-config
          mountPath: /opt/spinnaker/config/default
        - name: custom-config
          mountPath: /opt/spinnaker/config/custom
      volumes:
      - name: custom-config
        configMap:
          name: custom-config
      - name: default-config
        configMap:
          name: default-config
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations